# Generated by Django 2.2.16 on 2020-09-14 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Call', 'Call'), ('Line', 'Line'), ('Facebook', 'Facebook'), ('Email', 'Email'), ('Line_official', 'Line Official')], max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_type', models.CharField(choices=[('1', 'โรงพยาบาล'), ('3', 'ศูนย์บริการสาธารณสุข'), ('4', 'คลินิก')], max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('label', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resolution', models.TextField()),
                ('date_entered', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('case_pic', models.ImageField(blank=True, upload_to='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospitals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Hospitals')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Project')),
                ('project_subgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Project_subgroup')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Service')),
            ],
        ),
    ]
