# Generated by Django 2.2.16 on 2021-02-15 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcode', models.CharField(default='', max_length=140)),
                ('app_controlVersion', models.CharField(max_length=255)),
                ('hos_s_version', models.CharField(max_length=255)),
                ('hos_stock_version', models.CharField(max_length=255)),
                ('hos_ereferral_version', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='datatimeperiod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcode', models.CharField(max_length=255)),
                ('hname', models.CharField(max_length=255)),
                ('over5day', models.CharField(max_length=255)),
                ('under5day', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='error_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcode', models.CharField(max_length=255)),
                ('err_code', models.CharField(max_length=255)),
                ('err_detail', models.CharField(max_length=255)),
                ('total_denined', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_type', models.CharField(choices=[('1', 'โรงพยาบาล'), ('3', 'ศูนย์บริการสาธารณสุข'), ('4', 'คลินิก')], max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('active', models.CharField(max_length=255)),
                ('install_app', models.CharField(max_length=255)),
                ('training', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='model5_lookup_error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('err_code', models.TextField()),
                ('err_detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='model5_recap_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcode', models.CharField(max_length=255)),
                ('hname', models.CharField(max_length=255)),
                ('req_claimcode', models.CharField(max_length=255)),
                ('req_claim', models.CharField(max_length=255)),
                ('approved', models.CharField(max_length=255)),
                ('denined', models.CharField(max_length=255)),
                ('dataknow', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServerServiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sqlreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_Img', models.ImageField(upload_to='imagesReport/')),
                ('report_file', models.FileField(upload_to='reportFile/')),
                ('Memo', models.CharField(default='', max_length=255)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project_subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactPhone', models.CharField(default='', max_length=255)),
                ('FixIpAddress', models.CharField(default='', max_length=255)),
                ('datetimeSendServer', models.DateTimeField(blank=True, null=True)),
                ('Memo', models.CharField(default='', max_length=255)),
                ('ContactFirstName', models.CharField(default='', max_length=255)),
                ('ContactLastName', models.CharField(default='', max_length=255)),
                ('ContactEmail', models.CharField(default='', max_length=255)),
                ('datetimeReceiveServer', models.DateTimeField(blank=True, null=True)),
                ('ServerImage', models.ImageField(blank=True, upload_to='')),
                ('UseServer', models.CharField(default='', max_length=255)),
                ('dbBackup', models.CharField(default='', max_length=255)),
                ('datetimeCompleteServer', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('OperationSystem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.OperationSystem')),
                ('ServerBand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.ServerBand')),
                ('ServerServiceStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.ServerServiceStatus')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('database', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.database')),
                ('hospitals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Hospitals')),
                ('webServer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.WebServer')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resolution', models.TextField()),
                ('date_entered', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('statusCaseUpdate_at', models.DateTimeField(blank=True, null=True)),
                ('case_pic', models.ImageField(blank=True, upload_to='')),
                ('assign', models.CharField(default='', max_length=255)),
                ('assign_at', models.DateTimeField(blank=True, null=True)),
                ('assign_by', models.CharField(default='', max_length=255)),
                ('forward_by', models.CharField(default='', max_length=255)),
                ('ass_Solution', models.CharField(max_length=255)),
                ('forward_at', models.DateTimeField(blank=True, null=True)),
                ('priorityCase', models.CharField(default='', max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospitals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Hospitals')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Project')),
                ('project_subgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Project_subgroup')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Service')),
                ('status_Case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.StatusCase')),
            ],
        ),
    ]
