# Generated by Django 2.2.16 on 2020-12-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model5_lookup_error',
            name='err_detail',
            field=models.TextField(),
        ),
    ]
