# Generated by Django 2.2.16 on 2021-01-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileserver',
            name='UseServer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
