# Generated by Django 2.2.16 on 2021-01-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210115_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileserver',
            name='datetimeCompleteServer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
