# Generated by Django 2.2.16 on 2020-11-01 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200924_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_controlVersion', models.CharField(max_length=255)),
                ('hos_s_version', models.CharField(max_length=255)),
                ('hos_stock_version', models.CharField(max_length=255)),
                ('hos_ereferral_version', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('hospitals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Hospitals')),
            ],
        ),
    ]
