# Generated by Django 2.2.16 on 2021-01-17 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20210117_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='postgresVersion',
            new_name='database',
        ),
        migrations.RenameField(
            model_name='profileserver',
            old_name='posgresql',
            new_name='database',
        ),
        migrations.AddField(
            model_name='profileserver',
            name='dbBackup',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profileserver',
            name='webServer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.WebServer'),
        ),
    ]
