# Generated by Django 2.2.16 on 2020-11-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_controlversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlversion',
            name='hospitals',
        ),
        migrations.AddField(
            model_name='controlversion',
            name='hcode',
            field=models.CharField(default='', max_length=140),
        ),
    ]
