# Generated by Django 2.2.16 on 2020-12-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_model5_recap_report_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model5_recap_report',
            old_name='total',
            new_name='err_code',
        ),
    ]
