# Generated by Django 2.2.16 on 2020-12-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20201217_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model5_recap_report',
            old_name='err_code',
            new_name='err_cod',
        ),
    ]
