# Generated by Django 2.2.16 on 2021-01-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20210117_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileserver',
            name='case',
        ),
    ]
