# Generated by Django 2.2.16 on 2020-12-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20201217_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='error_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcode', models.CharField(max_length=255)),
                ('err_code', models.CharField(max_length=255)),
                ('err_detail', models.CharField(max_length=255)),
                ('total_denined', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
