# Generated by Django 2.2.16 on 2020-12-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_error_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error_detail',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
