# Generated by Django 2.2.16 on 2020-12-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20201219_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error_detail',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
