# Generated by Django 2.2.16 on 2020-12-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20201224_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataTimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcode', models.CharField(max_length=255)),
                ('hname', models.CharField(max_length=255)),
                ('over5day', models.CharField(max_length=255)),
                ('under5day', models.CharField(max_length=255)),
            ],
        ),
    ]
