# Generated by Django 2.2.16 on 2021-01-07 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_datatimeperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_subgroup',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Project'),
        ),
    ]
