# Generated by Django 2.2.16 on 2021-01-15 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_operationsystem_serverband_serverservicestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerBand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.ServerBand')),
            ],
        ),
    ]
