# Generated by Django 2.2.16 on 2021-01-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_profileserver_firstoperationsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileserver',
            name='ContactPhone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profileserver',
            name='FixIpAddress',
            field=models.CharField(default='', max_length=255),
        ),
    ]
