# Generated by Django 2.2.16 on 2021-01-15 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20210115_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileserver',
            name='hospitals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Hospitals'),
        ),
    ]
