# Generated by Django 2.2.16 on 2021-01-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_profileserver_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileserver',
            name='DatetimeComplete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
