# Generated by Django 2.2.16 on 2021-01-15 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_profileserver_datetimecomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileserver',
            name='ServerServiceStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.ServerServiceStatus'),
        ),
        migrations.AddField(
            model_name='profileserver',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Case'),
        ),
    ]
