# Generated by Django 2.2.16 on 2021-01-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20210115_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileserver',
            name='Memo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
