# Generated by Django 2.2.16 on 2021-01-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_profileserver_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileserver',
            name='ContactFirstName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profileserver',
            name='ContactLastName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
