# Generated by Django 2.2.16 on 2021-01-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20210115_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileserver',
            name='ContactEmail',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileserver',
            name='datetimeReceiveServer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
