# Generated by Django 2.2.16 on 2021-01-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20210115_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileserver',
            name='ContactEmail',
            field=models.CharField(default='', max_length=255),
        ),
    ]
