# Generated by Django 2.2.16 on 2021-01-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_auto_20210115_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileserver',
            old_name='FirstOperationSystem',
            new_name='OperationSystem',
        ),
    ]
