# Generated by Django 2.2.16 on 2021-01-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20210115_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileserver',
            name='ServerImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
