# Generated by Django 2.2.16 on 2021-01-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_profileserver_serverimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileserver',
            old_name='DatetimeComplete',
            new_name='datetimeSendServer',
        ),
    ]
